import { CAPABILITIES } from './data.mjs';
import { draftScope, findExamples, getCapability, listCapabilities, prepareDecisionPacket } from './core.mjs';

const CAPABILITY_ENUM = CAPABILITIES.map((capability) => capability.id);
const RO = Object.freeze({ readOnlyHint: true, untrustedContentHint: false });
const EXT = Object.freeze({ readOnlyHint: true, untrustedContentHint: true });
const LOCAL = Object.freeze({ readOnlyHint: false, untrustedContentHint: false });
const MAX_OBJECTIVE_LENGTH = 240;
const MAX_CONSTRAINTS = 8;
const MAX_CONSTRAINT_LENGTH = 160;

const schemas = {
  list_capabilities: { type: 'object', properties: { problem: { type: 'string', maxLength: 120, description: 'Raw natural-language need from the user, such as public-data operational dashboard or mobile field use.' }, delivery_pattern: { type: 'string', maxLength: 80, description: 'Requested delivery form in the user’s own words, such as dashboard, map, web application, or automation.' } }, additionalProperties: false },
  get_capability: { type: 'object', properties: { capability_id: { type: 'string', enum: CAPABILITY_ENUM, description: 'Exact capability ID returned by capability discovery; use the returned ID rather than inventing one.' } }, required: ['capability_id'], additionalProperties: false },
  find_examples: { type: 'object', properties: { capability_ids: { type: 'array', description: 'Exact capability IDs returned by discovery whose linked public evidence should be retrieved.', items: { type: 'string', enum: CAPABILITY_ENUM, description: 'One exact capability ID returned by capability discovery.' }, uniqueItems: true, maxItems: CAPABILITY_ENUM.length }, problem: { type: 'string', maxLength: 120, description: 'Raw natural-language need used to find public evidence through matching capability context.' } }, additionalProperties: false },
  draft_scope: { type: 'object', properties: { objective: { type: 'string', minLength: 3, maxLength: MAX_OBJECTIVE_LENGTH, description: 'Desired outcome in the user’s own words; preserve the outcome instead of translating it into implementation jargon.' }, capability_ids: { type: 'array', description: 'Evidence-backed capability IDs selected from discovery for this objective.', items: { type: 'string', enum: CAPABILITY_ENUM, description: 'One exact capability ID returned by capability discovery.' }, uniqueItems: true, minItems: 1, maxItems: CAPABILITY_ENUM.length }, constraints: { type: 'array', description: 'Natural-language requirements that must remain true in the proposed scope.', items: { type: 'string', maxLength: MAX_CONSTRAINT_LENGTH, description: 'One user constraint in plain language, such as Public data only or Mobile-first.' }, uniqueItems: true, maxItems: MAX_CONSTRAINTS } }, required: ['objective', 'capability_ids'], additionalProperties: false },
  prepare_decision_packet: { type: 'object', properties: { objective: { type: 'string', minLength: 3, maxLength: MAX_OBJECTIVE_LENGTH, description: 'Desired outcome in the user’s own words; preserve the outcome instead of translating it into implementation jargon.' }, capability_ids: { type: 'array', description: 'Evidence-backed capability IDs selected from discovery for this objective.', items: { type: 'string', enum: CAPABILITY_ENUM, description: 'One exact capability ID returned by capability discovery.' }, uniqueItems: true, minItems: 1, maxItems: CAPABILITY_ENUM.length }, constraints: { type: 'array', description: 'Natural-language requirements that must remain true in the proposed scope.', items: { type: 'string', maxLength: MAX_CONSTRAINT_LENGTH, description: 'One user constraint in plain language, such as Public data only or Mobile-first.' }, uniqueItems: true, maxItems: MAX_CONSTRAINTS } }, required: ['objective', 'capability_ids'], additionalProperties: false },
  stage_human_review: { type: 'object', properties: { objective: { type: 'string', minLength: 3, maxLength: MAX_OBJECTIVE_LENGTH, description: 'Desired outcome in the user’s own words; preserve the outcome instead of translating it into implementation jargon.' }, capability_ids: { type: 'array', description: 'Evidence-backed capability IDs selected from discovery for this objective.', items: { type: 'string', enum: CAPABILITY_ENUM, description: 'One exact capability ID returned by capability discovery.' }, uniqueItems: true, minItems: 1, maxItems: CAPABILITY_ENUM.length }, constraints: { type: 'array', description: 'Natural-language requirements that must remain true in the proposed scope.', items: { type: 'string', maxLength: MAX_CONSTRAINT_LENGTH, description: 'One user constraint in plain language, such as Public data only or Mobile-first.' }, uniqueItems: true, maxItems: MAX_CONSTRAINTS } }, required: ['objective', 'capability_ids'], additionalProperties: false }
};

function jsonResult(value) { return JSON.stringify(value); }
const compactAuthority = Object.freeze({ binding: false, external_action: false, persistence: false, human_review_required: true });
function compactList(result) { if (result.status !== 'OK') return { status: result.status, error: result.error, authority: compactAuthority }; return { status: result.status, records: result.records.map(({ id, name, short, evidence_count }) => ({ id, name, short, evidence_count })), authority: compactAuthority }; }
function compactCapability(result) { if (result.status !== 'OK') return { status: result.status, capability_id: result.capability_id, error: result.error, authority: compactAuthority }; const { id, name, summary, problem_types, delivery_patterns, evidence_ids, constraints, provenance } = result.record; return { status: result.status, record: { id, name, summary, problem_types, delivery_patterns, evidence_ids, constraints, provenance }, proof_boundary: result.proof_boundary, authority: compactAuthority }; }
function compactExamples(result) { if (result.status !== 'OK') return { status: result.status, error: result.error, authority: compactAuthority }; return { status: result.status, records: result.records.map(({ id, title, public_summary, capability_ids, public_url, proof_boundary, provenance }) => ({ id, title, public_summary, capability_ids, public_url, proof_boundary, provenance })), authority: compactAuthority }; }
function compactScope(result) { if (result.status !== 'OK') return result; return { status: result.status, draft: { objective: result.draft.objective, capability_ids: result.draft.selected_capability_ids, workstreams: result.draft.proposed_workstreams.map(({ id, name }) => ({ id, name })), evidence_ids: result.draft.evidence_ids, constraints: result.draft.proposed_workstreams[0]?.assumptions ?? [], open_questions: result.draft.open_questions, unknown_capability_ids: result.draft.unknown_capability_ids, authority: result.draft.authority }, authority: compactAuthority }; }
function compactPacket(result) { if (result.status !== 'READY_FOR_HUMAN_REVIEW') return result; return { status: result.status, packet: { objective: result.packet.objective, workstreams: result.packet.workstreams.map(({ id, name }) => ({ id, name })), evidence: result.packet.evidence_receipts.map(({ id, title, public_url, proof_boundary }) => ({ id, title, public_url, proof_boundary })), open_questions: result.packet.open_questions, decision_required: result.packet.decision_required, blocked: ['contact', 'submit', 'pay', 'sign', 'commit', 'account_mutation'], authority: result.packet.authority }, authority: compactAuthority }; }

export function createTools(bridge = {}) {
  const report = (name, input, result) => bridge.onToolResult?.({ name, input, result });
  const run = async (name, input, fn) => { const result = fn(input); report(name, input, result); return jsonResult(result); };
  return [
    { name: 'list_capabilities', title: 'List evidence-backed capabilities', description: 'Discover Maps + Apps capabilities that match a user’s raw natural-language need or delivery form. Returns IDs, short summaries, and public-evidence counts for selection.', inputSchema: schemas.list_capabilities, annotations: RO, execute: async (input) => run('list_capabilities', input, (value) => compactList(listCapabilities(value))) },
    { name: 'get_capability', title: 'Inspect one capability', description: 'Inspect one capability ID returned by discovery. Returns its fit, linked evidence IDs, constraints, provenance, and proof boundary for claim verification.', inputSchema: schemas.get_capability, annotations: EXT, execute: async (input) => run('get_capability', input, (value) => compactCapability(getCapability(value))) },
    { name: 'find_examples', title: 'Find public proof', description: 'Retrieve public evidence linked to selected capability IDs or a raw natural-language need, including URLs, provenance, and proof boundaries for claim checking.', inputSchema: schemas.find_examples, annotations: EXT, execute: async (input) => run('find_examples', input, (value) => compactExamples(findExamples(value))) },
    { name: 'draft_scope', title: 'Draft a bounded scope', description: 'Draft an early nonbinding workstream proposal from the user’s objective, selected capability IDs, and constraints. Returns scope and open questions only; it does not build or stage the final review packet.', inputSchema: schemas.draft_scope, annotations: RO, execute: async (input) => run('draft_scope', input, (value) => compactScope(draftScope(value))) },
    { name: 'prepare_decision_packet', title: 'Prepare a decision packet', description: 'Return an evidence-backed decision packet to the agent without changing visible page state. Use when the user wants the packet inspected before any visible human-review handoff.', inputSchema: schemas.prepare_decision_packet, annotations: RO, execute: async (input) => run('prepare_decision_packet', input, (value) => compactPacket(prepareDecisionPacket(value))) },
    { name: 'stage_human_review', title: 'Stage packet for human review', description: 'Use when the user asks to show, place, or stage the packet in the visible human-review workspace. Updates only reversible current-tab UI state so the person can inspect and edit it.', inputSchema: schemas.stage_human_review, annotations: LOCAL, execute: async (input) => { const result = prepareDecisionPacket(input); bridge.stageReview?.(input, result); report('stage_human_review', input, result); return jsonResult({ status: result.status, staged_in_visible_ui: result.status === 'READY_FOR_HUMAN_REVIEW', persistence: false, external_action: false, decision_required: result.packet?.decision_required ?? null }); } }
  ];
}

export async function registerCapabilityTools(doc = document, bridge = {}) {
  const modelContext = doc?.modelContext;
  if (!modelContext?.registerTool) return { status: 'WEBMCP_UNAVAILABLE', tool_count: 0, tool_names: [], abort: () => {} };
  const controller = new AbortController();
  const tools = createTools(bridge);
  for (const tool of tools) await modelContext.registerTool(tool, { signal: controller.signal });
  return { status: 'REGISTERED', tool_count: tools.length, tool_names: tools.map((tool) => tool.name), abort: () => controller.abort() };
}
